{
    "task" : "anet",
    "paths": {
        "ckpt_dir": "./ckpt",
        "cache_dir" : "./data_pkl/",
        "feature_path": "/storage_fast/rjliang/activitynet/i3d",
        "glove_path": "/storage_fast/rjliang/glove/glove.840B.300d.txt",
        "train_path": "./data/anet_i3d_gt/train.json",
        "test_path": "./data/anet_i3d_gt/test.json",
        "val_path": ""
    },
  "train": {
    "epochs": 100,
    "batch_size": 16,
    "lr": 0.0001,
    "clip_norm": 1.0
  },
  "model": {
    name: "SeqPAN",
    max_vlen: 100,
    max_tlen: 30,
    vdim: 1024,
    dim: 128,
    num_heads: 8,
    word_dim: 300,
    char_dim: 100,
    droprate: 0.1,
    attn_layer: 2
  },
    "loss":
    {   match_lambda: 1.0, 
        tau: 0.3,
        no_gumbel: true,
    }
}